
server:
  port: 8080
spring:
  application:
    name:  gateway
  cloud:
    gateway:
      routes:

        - id: USER-SERVICE
          uri: http://localhost:8085/
          predicates:
            Path=/api/user/**
        - id: ADRESSE-SERVICE
          uri: http://localhost:8083/
          predicates:
            Path=/api/adresse/**
